# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '3. GoodList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3. GoodList
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
end
